name: Label Issues (Permissions Example)
on:
  issues:
    types:
      - opened
jobs:
  assign-label:
#We add permission on a job level
#This workflow will be able to edit this issue, but it won't be able to explore the code of repo or manipulate actions and other things
    permissions:
      issues: write
#Only this permission is granted, all other permissions are not granted - default changes!
#We simply add additional layer of protection
#Any actions that I intend not to do - I blocked by using permissions 
    runs-on: ubuntu-latest
    steps:
      - name: Assign label
        if: contains(github.event.issue.title, 'bug')
        run: |
          curl -X POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels \
          -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          -H 'content-type: application/json' \
          -d '{
              "labels": ["bug"]
            }' \
          --fail


#As we can see in Issues - my issues Yet another bug assigned label (a label was added a bug in a red color).
#All workflows passess successfully
#A GITHUB_TOKEN permission includes only permission to read issues (line 11)
#It is reason why when we open Issues in GitHub, this workflow fails
#We need to provide this token (GITHUB_TOKEN) with appropriate permissions.
#Thanks to this, this token is attached to do succeed.
#We use always secrets.GITHUB_TOKEN, but it is the first time we have seen it,
#because we actually send a request to GitHub's API manually.
#In addition, all actions are used GitHub's API under the hood and use this token secret (lines 22).
#They have been regulated with permission set by us (lines 9).
#In our case we have permissions only read. It is reason why this workflows fail when we open Issues.